---
- name: Generate and copy SSH key to hosts
  hosts: all
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Generate SSH key pair
      ansible.builtin.openssh_keypair:
        path: ~/.ssh/id_rsa
        force: no
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Copy SSH public key to authorized_keys
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/authorized_keys
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
